joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.1
    autorerepeat_rate: 20.0

teleop_twist_joy_node:
  ros__parameters:
    require_enable_button: false

    # --- ĐIỀU KHIỂN TIẾN LÙI (CẦN TRÁI) ---
    axis_linear:
      x: 1
    scale_linear:
      x: 0.8         

    # --- ĐIỀU KHIỂN ĐÁNH LÁI (CẦN TRÁI VỪA GẠT NGANG) ---
    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.5        # Trả về số dương chuẩn mực